name: Update secret
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/update-token.yaml'
  workflow_dispatch:

jobs:
    update-secter:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: write
        steps:
          - id: 'checkout'
            uses: 'actions/checkout@v4'
          
          - id: 'auth'
            uses: 'google-github-actions/auth@v2'
            with:
              workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
              service_account: ${{ secrets.WORKLOAD_IDENTITY_SA }}

          - id: 'secrets'
            uses: 'google-github-actions/get-secretmanager-secrets@v2'
            with:
              secrets: |-
                token:${{ secrets.GSM_SECRET }}

          - name: 'Create secret manifest'
            run: |
                 echo -n '${{ steps.secrets.outputs.token }}' | base64 - > token
                 cat <<EOF > kustomization.yaml
                 apiVersion: kustomize.config.k8s.io/v1beta1
                 kind: Kustomization
                 secretGenerator:
                 - name: ${{ vars.SECRET_NAME }}
                   namespace: ${{ vars.SECRET_NAMESPACE }}
                   options:
                     disableNameSuffixHash: true
                   files:
                   - token
                   type: "Opaque"
                 EOF
          - name: 'Kustomize Build' 
            uses: karancode/kustomize-github-action@master
            with:
              kustomize_version: '5.3.0'
              kustomize_build_dir: '.'
              kustomize_output_file: "${{ vars.SECRET_NAME }}.yaml"
          - name: 'Sops Binary Installer'
            uses: mdgreenwald/mozilla-sops-action@v1.4.1
            with:
              version: '3.8.1'
            id: install
          - name: 'Sops Runner'
            run: |
                 sops -e -gcp-kms ${{ secrets.KMS_CRYPTO_KEY }} -encrypted-regex '^(token)$' ${{ vars.SECRET_NAME }}.yaml>./clusters/${{ vars.SECRET_NAMESPACE }}/${{ vars.SECRET_NAME }}-enc.yaml
                 rm token ${{ vars.SECRET_NAME }}.yaml kustomization.yaml *.json
          - name: 'Push ecrypted manifest'
            run: |
                 git config user.name github-actions
                 git config user.email github-actions@github.com
                 git add clusters/${{ vars.SECRET_NAMESPACE }}/${{ vars.SECRET_NAME }}-enc.yaml
                 git commit -m "update ${{ vars.SECRET_NAME }}-enc.yaml"
                 git push