apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot
  namespace: kbot
spec:
  interval: 1m0s
  ref:
    branch: develop
  url: https://github.com/bergshrund/kbot